### ISSUE TITLE
there is new major version (2.0) of nodejs-redis => mosca is crashing

### ISSUE THREAD

**Issue by JoalePampala** [mcollina/mosca#363] opened 2015-10-01 23:52 UTC
after client connect

/opt/easyride/node_modules/mosca/node_modules/ascoltatori/lib/redis_ascoltatore.js:135
        topic = topic.replace(new RegExp('/$'), '');
                      ^
TypeError: topic.replace is not a function

**Comment by mcollina** [comment] 2015-10-02 06:29
The problem is within ascoltatori. Why don't you try to fix that?

**Comment by JoalePampala** [comment] 2015-10-02 13:27
Ok, boss. I will try.

**Comment by JoalePampala** [comment] 2015-10-11 13:58
https://github.com/mcollina/ascoltatori/pull/136

**Comment by behrad** [comment] 2015-10-11 14:15
And as a proposal: Are you thinking @mcollina of switching to `ioredis` in new Mosca or Aedes redis persistence? Since thats a newer and more stable fork of node_redis

**Comment by JoalePampala** [comment] 2015-10-13 21:28
@behrad https://github.com/NodeRedis/node_redis/releases/tag/v.2.2.0

**Comment by behrad** [comment] 2015-10-14 06:07
There's not performance issues, you can find there (in issues) that node_redis still have some stability problems, and some users of Kue have reported ioredis is more robust.
Another important point is node_redis is not supporting Redis Cluster, which again ioredis does well.
This are important requirements to mosca for improved redis backend support.

**Comment by mcollina** [comment] 2015-10-14 06:14
If you want to send over PRs for migrating to ioredis, I'll merge them.
Il giorno mer 14 ott 2015 alle 08:07 Behrad <notifications@github.com> ha
scritto:

**Comment by mcollina** [comment] 2016-01-19 08:54
Fixed in v1.0.0

**Closed by mcollina** 2016-01-19 08:54 UTC
