### ISSUE TITLE
Mosca crash per incoming request

### ISSUE THREAD

**Issue by KyleHsiao** [mcollina/mosca#476] opened 2016-05-17 21:59 UTC
We are running Mosca v1.3 in docker container on Docker Swarm using redis as broker and persistent storage. The service keep crashing on each incoming request:

{"name":"mosca","hostname":"95cf7a08e67d","pid":6,"level":30,"mqtt":1883,"msg":"server started","time":"2016-05-17T21:38:05.935Z","v":0}
/usr/src/app/mosca/lib/persistence/abstract.js:105
        client.emit("error", err);
               ^

TypeError: client.emit is not a function
    at /usr/src/app/mosca/lib/persistence/abstract.js:105:16
    at /usr/src/app/mosca/lib/persistence/redis.js:319:9
    at /usr/src/app/mosca/node_modules/async/lib/async.js:726:13
    at /usr/src/app/mosca/node_modules/async/lib/async.js:52:16
    at done (/usr/src/app/mosca/node_modules/async/lib/async.js:241:17)
    at /usr/src/app/mosca/node_modules/async/lib/async.js:44:16
    at /usr/src/app/mosca/node_modules/async/lib/async.js:723:17
    at /usr/src/app/mosca/node_modules/async/lib/async.js:167:37
    at Object.callbackOrEmit [as callback_or_emit] (/usr/src/app/mosca/node_modules/redis/lib/utils.js:73:9)
    at RedisClient.return_error (/usr/src/app/mosca/node_modules/redis/index.js:622:11)

Any idea about it?

**Comment by KyleHsiao** [comment] 2016-05-17 23:48
Also resulted in the following error on incoming request:

SyntaxError: Unexpected token u
    at Object.parse (native)
    at /usr/src/app/mosca/lib/persistence/redis.js:304:17
    at Object.callbackOrEmit [as callback_or_emit] (/usr/src/app/mosca/node_modules/redis/lib/utils.js:73:9)
    at RedisClient.return_error (/usr/src/app/mosca/node_modules/redis/index.js:622:11)
    at HiredisReplyParser.RedisClient.reply_parser.Parser.returnError (/usr/src/app/mosca/node_modules/redis/index.js:149:18)
    at HiredisReplyParser.execute (/usr/src/app/mosca/node_modules/redis/node_modules/redis-parser/lib/hiredis.js:28:18)
    at Socket.<anonymous> (/usr/src/app/mosca/node_modules/redis/index.js:223:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)

**Comment by mcollina** [comment] 2016-05-30 12:47
I cannot reproduce the `Unexpected token u` error, can you please upload something to reproduce it? It can be a sample project with instructions.

**Comment by mcollina** [comment] 2016-06-18 15:10
Should be fixed in v2.0.0.

**Closed by mcollina** 2016-06-18 15:10 UTC
