### ISSUE TITLE
Ability to Alter Message

### ISSUE THREAD

**Issue by ccravens** [mcollina/mosca#465] opened 2016-05-02 17:14 UTC
I'm wondering if there is a way to alter messages that are published? For example, if I have a device that sends the following message to topic 'devices/ping':

`'{count:0}'`

and in the server I was able to capture that published message, and alter its contents to:

`'{count:1}'`

and then all clients subscribed to 'devices/ping' would receive the following message:

`'{count:1}'`

I would expect something like this within the "published" event handler:
```
	server.on('published', function(packet, callback) {
             packet.payload = '{count:1}';
             callback(packet); // Here we are passing back packet with the updated payload (message) to send to the clients
	});
```

**Comment by mcollina** [comment] 2016-05-02 19:48
This is a duplicate of https://github.com/mcollina/mosca/issues/368.

It will be a nice feature to add. However, this will happen when I do finish the Aedes rewrite.
If anybody wants to send a PR, I'll be more than happy to review.

**Closed by mcollina** 2016-05-02 19:48 UTC

**Comment by ccravens** [comment] 2016-05-02 21:45
Yah, this is a really nice feature and is pretty critical to our immediate needs and I"m sure would be important to others as well. I am happy to jump on and submit a PR to develop towards.

I'll move this discussion to #368
