### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by eladnava** [mcollina/mosca#319] opened 2015-07-24 12:47 UTC
Hi there,
First off, thank you for all the contributors and maintainers of this great package.

I am trying to investigate a possible memory leak that may be originating from mosca (v0.31.0). I am using the following code to run a test broker:

**server.js**

    var mosca = require('mosca');

    var config =
    {
        port: 1883
    };

    var server = new mosca.Server(config);

    server.on('ready', function()
    {
        console.log('mqtt.port: ' + config.port);
    });

    // Run the garbage collector every 5 seconds
    setInterval( function()
    {
        global.gc();
        console.log('gc');
    }, 5000);

And the following code, using MQTT.js, to connect dummy clients to the broker:

**client.js**

    var mqtt    = require('mqtt');
    var async   = require('async');
    var crypto   = require('crypto');
    
    // Connected devices
    var connected = 0;
    
    // Tmp tasks array for async
    var tasks = [];
    
    // Fill the array up with tasks
    for ( var i = 0; i < 15000; i++ )
    {
        tasks.push( i );
    }
    
    // Connect one after the other
    async.eachLimit(tasks, 50, function(total, callback)
    {
        // Create client & connect locally
        var client = mqtt.connect( 'mqtt://127.0.0.1', { clientId: crypto.randomBytes(11).toString('hex') } );
    
        // Log connection
        client.on( 'connect', function()
        {
            // Increment counter
            connected++;
    
            // Log it
            console.log( connected );
    
            // All done here
            callback();
        } );
    });

When I `node --expose-gc server.js` to start mosca and wait 10 seconds (for 2 consecutive GCs), memory usage is at 3.8%. (No clients yet)

I then `node client.js` to connect 15000 clients to mosca. When they're all connected, I shut down the client and the connections start draining out.

However, memory usage never returns to the original value before the 15k connections.

**Memory usage:**
`node --expose-gc server.js` -> 3.6%
2x `global.gc()` -> 3.8%
`node client.js` (15k connections) -> 39%
`kill client.js` -> 20%
25x `global.gc()` -> 7%
100x `global.gc()` -> 6.4%

As you can see from the memory usage, after killing all the clients and running the GC counless times, the memory usage never returns to 3.8%, the original value before the 15k connections. Even though all the connections have been terminated, something in mosca is not being collected.

This is the `memwatch.HeapDiff()` comparison from before the clients connected, and after 10 garbage collections post-disconnection:

	{ before:
	   { nodes: 62970,
		 time: Fri Jul 24 2015 12:41:07 GMT+0000 (UTC),
		 size_bytes: 27775944,
		 size: '26.49 mb' },
	  after:
	   { nodes: 62683,
		 time: Fri Jul 24 2015 12:41:48 GMT+0000 (UTC),
		 size_bytes: 29458792,
		 size: '28.09 mb' },
	  change:
	   { size_bytes: 1682848,
		 size: '1.6 mb',
		 freed_nodes: 7227,
		 allocated_nodes: 6940,
		 details:
		  [ { size: '596.54 kb',
			  '-': 2529,
			  what: 'Array',
			  size_bytes: 610856,
			  '+': 3638 },
			{ size: '192 bytes',
			  '-': 0,
			  what: 'Buffer',
			  size_bytes: 192,
			  '+': 4 },
			{ size: '416 bytes',
			  '-': 0,
			  what: 'BufferList',
			  size_bytes: 416,
			  '+': 4 },
			{ size: '504 bytes',
			  '-': 0,
			  what: 'Client',
			  size_bytes: 504,
			  '+': 4 },
			{ size: '11.39 kb',
			  '-': 5,
			  what: 'Closure',
			  size_bytes: 11664,
			  '+': 167 },
			{ size: '36.77 kb',
			  '-': 1673,
			  what: 'Code',
			  size_bytes: 37656,
			  '+': 1518 },
			{ size: '384 bytes',
			  '-': 0,
			  what: 'Connection',
			  size_bytes: 384,
			  '+': 4 },
			{ size: '768 bytes',
			  '-': 0,
			  what: 'DestroyableTransform',
			  size_bytes: 768,
			  '+': 8 },
			{ size: '-24 bytes',
			  '-': 1,
			  what: 'Error',
			  size_bytes: -24,
			  '+': 0 },
			{ size: '352 bytes',
			  '-': 0,
			  what: 'Logger',
			  size_bytes: 352,
			  '+': 4 },
			{ size: '1024 kb',
			  '-': 1,
			  what: 'Native',
			  size_bytes: 1048576,
			  '+': 2 },
			{ size: '-32 bytes',
			  '-': 11,
			  what: 'Number',
			  size_bytes: -32,
			  '+': 9 },
			{ size: '2.2 kb',
			  '-': 2,
			  what: 'Object',
			  size_bytes: 2256,
			  '+': 85 },
			{ size: '344 bytes',
			  '-': 0,
			  what: 'Packet',
			  size_bytes: 344,
			  '+': 5 },
			{ size: '256 bytes',
			  '-': 0,
			  what: 'Parser',
			  size_bytes: 256,
			  '+': 4 },
			{ size: '3.82 kb',
			  '-': 0,
			  what: 'ReadableState',
			  size_bytes: 3912,
			  '+': 23 },
			{ size: '32 bytes',
			  '-': 1,
			  what: 'SlowBuffer',
			  size_bytes: 32,
			  '+': 2 },
			{ size: '704 bytes',
			  '-': 0,
			  what: 'Socket',
			  size_bytes: 704,
			  '+': 4 },
			{ size: '-23.34 kb',
			  '-': 537,
			  what: 'String',
			  size_bytes: -23896,
			  '+': 188 },
			{ size: '288 bytes',
			  '-': 0,
			  what: 'Timeout',
			  size_bytes: 288,
			  '+': 4 },
			{ size: '600 bytes',
			  '-': 0,
			  what: 'TransformState',
			  size_bytes: 600,
			  '+': 9 },
			{ size: '320 bytes',
			  '-': 0,
			  what: 'Writable',
			  size_bytes: 320,
			  '+': 4 },
			{ size: '4 kb',
			  '-': 0,
			  what: 'WritableState',
			  size_bytes: 4096,
			  '+': 27 },
			[length]: 23 ] } }

Is there anything else I can do to help debug this issue? Are you aware of this behavior? 

Thanks,
Elad

**Comment by mcollina** [comment] 2015-07-24 13:31
It seems to me that most of that memory usage is due to optimized code (the only sizable piece is that Native entry). Moreover, the node.js GC is quite lazy, so it might even not clean up everything (just because it has plenty of RAM available).

You should try repeating that cycle many times and verify the memory usage over time.

**Comment by eladnava** [comment] 2015-07-24 13:40
Hi matteo,
Thanks for your quick response!

I was able to reproduce this behavior multiple times, also using the "mqtt" package instead of "mosca", as well as the "mqtt-connection" library to create a simple MQTT broker. Similar behavior in all of them. Memory usage never returns to the original value before the connections were made.

The problem with this leak is that it's causing my production apps to crash, because over a few days, the same overall number of clients (about 3000) keep connecting and disconnecting due to reception changes, and memory usage just keeps growing all the time, until the Linux OOM killer shuts down the node process. So I think that the GC is not lazy when it's life or death for node.

Here is a screenshot of the "Memory Available" graph over a whole week of running mosca with about 3,000 clients, reconnecting every few hours.
![leak](https://cloud.githubusercontent.com/assets/4394189/8875497/4953e5f6-3222-11e5-800a-542cb65ab1d6.png)

The peaks are when node is killed and restarted due to OOM.

Regarding the native entry, is there any way to prevent that buildup? It may be the source of the "memory leak" symptom.

**Comment by mcollina** [comment] 2015-07-24 13:54
@eladnava that's exactly the report we should look into.

Which Node version are you using? Is the CPU at high load?
0.10 is usually really bad on memory handling, so a good try might be node 0.12 or iojs
(It might be an easy win).

Anyway, the problem seems to be in [mqtt-connection](http://npm.im/mqtt-connection) (it's used in Mosca), or even in [mqtt-packet](http://npm.im/mqtt-packet).

Another try can be https://github.com/mcollina/aedes, which is built on top of mqtt-packet (think about it as Mosca v2). In this way we can know if the issue is in mqtt-packet.

**Comment by eladnava** [comment] 2015-07-24 14:07
@mcollina just tried the test with node 0.12.7. Unfortunately, exact same behavior. (verified version with `node -v`). 

Re: CPU, when the clients are connecting rapidly, yes, it can reach 80% CPU. However, as soon as I terminate the connections, CPU drops to about 0 - 2%. Memory is not released. By the way, everything is being run on a t2.micro instance on AWS. It is a Ubuntu server with nothing else on it. Created just for the tests.

Also, I did just give aedes a try, and the symptoms are the same. Not sure what else to try.

**Comment by mcollina** [comment] 2015-07-24 14:20
There is nothing simple to try, there is a memory leak somewhere that make a https://github.com/mqttjs/mqtt-packet/blob/master/parser.js leak. In the above heapdiff, there are 4 parsers left around, 4 connections and some more stuff.

Probably the best course of action is to focus on mqtt-connection/mqtt-parser and see what can be going on there.

**Comment by eladnava** [comment] 2015-07-24 14:22
@mcollina  I also tried the `mqtt-server` package, which does not use `mqtt-packet` module, is it possible that the leak is not in `mqtt-packet`? Or maybe there's another leak in `mqtt-server` package?

**Comment by mcollina** [comment] 2015-07-24 14:24
[mqtt-server](http://npm.im/mqtt-server) uses [mqtt-connection](http://npm.im/mqtt-connection), which uses [mqtt-packet](http://npm.im/mqtt.packet).

**Comment by eladnava** [comment] 2015-07-24 14:58
By the way, it is completely reproducible. I just got an almost idential `HeapDiff` when I ran the test again.

When I tried connecting 30k clients instead of 15k, the native code doubled to 2mb.

Array didn't change much (581kb vs 608kb), Code (30kb vs 134kb) and finally Closure (11kb - no changes here).

So if we were to look into `mqtt-packet`, I'd say that we should try to prevent native memory buildup. Any idea what could be causing it?

**HeapDiff() of 30k clients**

	{ before:
	   { nodes: 61251,
		 time: Fri Jul 24 2015 14:48:59 GMT+0000 (UTC),
		 size_bytes: 27466472,
		 size: '26.19 mb' },
	  after:
	   { nodes: 61577,
		 time: Fri Jul 24 2015 14:51:22 GMT+0000 (UTC),
		 size_bytes: 30279584,
		 size: '28.88 mb' },
	  change:
	   { size_bytes: 2813112,
		 size: '2.68 mb',
		 freed_nodes: 6841,
		 allocated_nodes: 7167,
		 details:
		  [ { size_bytes: 623584,
			  size: '608.97 kb',
			  '-': 2418,
			  '+': 3751,
			  what: 'Array' },
			{ size_bytes: 192,
			  size: '192 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Buffer' },
			{ size_bytes: 416,
			  size: '416 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'BufferList' },
			{ size_bytes: 504,
			  size: '504 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Client' },
			{ size_bytes: 11664,
			  size: '11.39 kb',
			  '-': 5,
			  '+': 167,
			  what: 'Closure' },
			{ size_bytes: 137624,
			  size: '134.4 kb',
			  '-': 1605,
			  '+': 1610,
			  what: 'Code' },
			{ size_bytes: 384,
			  size: '384 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Connection' },
			{ size_bytes: 768,
			  size: '768 bytes',
			  '-': 0,
			  '+': 8,
			  what: 'DestroyableTransform' },
			{ size_bytes: -24,
			  size: '-24 bytes',
			  '-': 1,
			  '+': 0,
			  what: 'Error' },
			{ size_bytes: 352,
			  size: '352 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Logger' },
			{ size_bytes: 2097152,
			  size: '2 mb',
			  '-': 1,
			  '+': 3,
			  what: 'Native' },
			{ size_bytes: -32,
			  size: '-32 bytes',
			  '-': 11,
			  '+': 9,
			  what: 'Number' },
			{ size_bytes: 2256,
			  size: '2.2 kb',
			  '-': 2,
			  '+': 85,
			  what: 'Object' },
			{ size_bytes: 344,
			  size: '344 bytes',
			  '-': 0,
			  '+': 5,
			  what: 'Packet' },
			{ size_bytes: 256,
			  size: '256 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Parser' },
			{ size_bytes: 3912,
			  size: '3.82 kb',
			  '-': 0,
			  '+': 23,
			  what: 'ReadableState' },
			{ size_bytes: 64,
			  size: '64 bytes',
			  '-': 1,
			  '+': 3,
			  what: 'SlowBuffer' },
			{ size_bytes: 704,
			  size: '704 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Socket' },
			{ size_bytes: -20720,
			  size: '-20.23 kb',
			  '-': 525,
			  '+': 190,
			  what: 'String' },
			{ size_bytes: 288,
			  size: '288 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Timeout' },
			{ size_bytes: 600,
			  size: '600 bytes',
			  '-': 0,
			  '+': 9,
			  what: 'TransformState' },
			{ size_bytes: 320,
			  size: '320 bytes',
			  '-': 0,
			  '+': 4,
			  what: 'Writable' },
			{ size_bytes: 4096,
			  size: '4 kb',
			  '-': 0,
			  '+': 27,
			  what: 'WritableState' },
			[length]: 23 ] } }

**Comment by mcollina** [comment] 2015-07-24 15:23
Probably a circular reference?

The full stack is leaking "Client, Socket, Connection, Parser" at a rate of 4 every 30K clients, which is about 2-3 MB of memory due to buffers.

**Comment by mcollina** [comment] 2015-07-24 15:25
Probably we might empty the parser once the the socket is closed.

**Comment by behrad** [comment] 2015-07-24 15:25
:+1: @mcollina

**Comment by mcollina** [comment] 2015-07-24 15:27
@eladnava can you try to reproduce the issue just using mqtt-packet and the net module?

**Comment by eladnava** [comment] 2015-07-24 15:51
@mcollina any chance you have sample server code with mqtt-packet?

**Comment by mcollina** [comment] 2015-07-24 16:01
the best bet is Aedes.

But just create a new Parser and write all incoming data in it. That should be enough to cause the issue.

**Comment by mcollina** [comment] 2015-07-24 21:54
I cannot reproduce it on iojs, which might be a good/bad thing at the same time.

**Comment by mcollina** [comment] 2015-07-24 22:07
I can confirm this is happening on v0.10.40.

**Comment by mcollina** [comment] 2015-07-24 22:10
Actually, this is incorrect. After a few rounds the memory goes down again, extremely weird.

**Comment by mcollina** [comment] 2015-07-24 22:12
I'm leaving a script hammering a Mosca instance for the whole night, let's see tomorrow the memory usage.

**Comment by mcollina** [comment] 2015-07-25 05:33
I left a script hammering a Mosca process for the whole night:  connect 15k clients, closing them, wait 30 sec, repeat. The memory usage at end it is still at 70 MB of RAM.

Tested on Node 0.10.40. So, I am not able to reproduce your memory leak @eladnava.

**Comment by cfan8** [comment] 2015-07-25 05:58
I'm also using mosca on production. I similarly noticed a growing number of memory use but I can't confirm that since the GC is also a big cause. Watching this issue.

**Comment by mcollina** [comment] 2015-07-25 06:22
Also on iojs 2.4.0 I cannot reproduce with the given scripts.

I am not saying that there is no leak, just that it does not happen at connection level.

Side note: Aedes is giving me a 50% memory reduction at peak (150MB of RAM for 15k connections, vs 310MB for Mosca).

**Comment by eladnava** [comment] 2015-07-25 15:44
@mcollina what is the memory usage when the broker starts (before clients connect)? Does the memory usage return to the original memory after all the clients disconnect?

**Comment by mcollina** [comment] 2015-07-25 16:35
Around 67MB, and yes, it goes back there (after a few rounds, the next one
goes to 69, 71 and then back to 67).
Il giorno sab 25 lug 2015 alle 17:44 eladnava <notifications@github.com> ha
scritto:

**Comment by eladnava** [comment] 2015-07-26 15:07
I just noticed even weirder behavior. I tried connecting 25k clients. Mosca memory reached 50%. When I disconnected them by shutting down the `client.js`, memory dropped to 46% and stayed there for more than 100x GCs (it never dropped further than that.)

Tried on both node v0.10.25 and iojs 2.4.0. Same behavior.

Can you try connecting 25k clients and see how it behaves for you?

**Comment by mcollina** [comment] 2015-07-26 16:34
Connecting 25k or 15k should not change anything if there is a leak. It's
probably some bad decision making the GC is doing. Running the bench again
should 'fix' the memory consumption, the process should not crash.

Yes, Mosca has some weird memory usage, which I am working to fix (by
rewriting).

I won't have time to investigate this any further in the next few weeks.
Il giorno dom 26 lug 2015 alle 17:07 eladnava <notifications@github.com> ha
scritto:

**Comment by cfan8** [comment] 2015-07-27 01:15
@eladnava The memory usage is also related to the clients. If you shutdown the all the clients on one machine at a time, the OS may not be able to close all connections. From the server perspective, the connections are still active, and will only be closed after the heartbeat timed out. Have you got a counter at the server side to see the number of active connections ?

**Comment by eladnava** [comment] 2015-07-27 05:33
@cfan8 you are right with this theory. I checked `cat /proc/net/sockstat` and the connections were still active, and that's why the memory wasn't freed. However, in my previous tests (with the 15k clients), the connections were killed immediately when closing the script, so that's strange. I'll try again and update.

**Comment by cfan8** [comment] 2015-08-05 01:10
Hi @eladnava , have you got more information on this issue?

**Comment by eladnava** [comment] 2015-08-05 08:31
@cfan8 I have not got another chance to re-test. Can you try to reproduce it on your machine with my sample code?

**Comment by mcollina** [comment] 2015-08-05 08:42
Closing for now, feel free to reopen if needed.

**Closed by mcollina** 2015-08-05 08:42 UTC

**Comment by eladnava** [comment] 2018-09-04 08:59
Hi @mcollina and @behrad,
Hope you're doing great!

I'm still experiencing some kind of memory leak, and I'd like to take another stab at this. @mcollina you previously suggested the following:

```
Probably we might empty the parser once the the socket is closed.
```

How do you go about doing this? Any kind of sample code or points would be appreciated. 👍

**Comment by andrew-ballard1** [comment] 2019-06-13 20:30
Anyone else here due to similar issues (mqtt, memory leaks, restarts), https://github.com/nodejs/help/issues/1518#issuecomment-423944893 
is worth a read

**Comment by eladnava** [comment] 2019-06-14 10:30
@andrew-ballard1 Haha yup, that's me opening both issues, this one and the node in `nodejs/help`, while I was debugging a memory leak I thought was related to `mosca` or `mqttjs`.
